set number
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
filetype on
filetype indent on
filetype plugin on
syntax on
set autoindent
set smartindent
set ambiwidth=double
set hlsearch
set undofile
set splitright
set clipboard=unnamedplus,autoselect
set backspace=indent,eol,start
set background=dark
set foldmethod=marker
highlight Normal ctermbg=none
set updatetime=1000
set autoread
colorscheme elflord
if &compatible
  set nocompatible
endif
set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/.vim/dein'))

call dein#add('Shougo/dein.vim')
call dein#add('Shougo/vimproc.vim', {'build': 'make'})

call dein#add('rust-lang/rust.vim')
call dein#add('tyru/skk.vim')
call dein#add('bronson/vim-trailing-whitespace')
call dein#add('itchyny/lightline.vim')

call dein#end()

syntax on

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
set laststatus=2
