# zsh
autoload -Uz colors
colors
PROMPT='%F{green}[%c@%m]%f '

HISTSIZE=5000
SAVEHIST=50000
HISTTIMEFORMAT='%Y-%m-%dT%H:%M:%S'
HISTFILE=${HOME}/.zsh_history
setopt EXTENDED_HISTORY
setopt hist_no_store
setopt hist_reduce_blanks
setopt share_history

alias g11='g++ --std=c++11 -Wall -O2'
alias gosh='rlwrap gosh'
alias ocaml='rlwrap ocaml'

autoload -U compinit && compinit

# homebrew
export HOMEBREW_NO_ANALYTICS=1

# Common Lisp
alias sbcl='rlwrap sbcl'

source ~/.zshrc.local
