# zsh
autoload -Uz colors
colors
PROMPT='%F{green}[%c@%m]%f '

HISTSIZE=5000
SAVEHIST=50000
HISTTIMEFORMAT='%Y-%m-%dT%H:%M:%S'
HISTFILE=${HOME}/.zsh_history
PATH=$HOME/local/bin:$HOME/local/bin2:$PATH
setopt EXTENDED_HISTORY
setopt hist_no_store
setopt hist_reduce_blanks
setopt share_history

alias g11='g++ --std=c++11 -Wall -O2'
alias gosh='rlwrap gosh'
alias ocaml='rlwrap ocaml'

autoload -U compinit && compinit
export TERM=screen-256color

# homebrew
export HOMEBREW_NO_ANALYTICS=1

# Common Lisp
alias sbcl='rlwrap sbcl'

# Go (golang)
export GOPATH=$HOME/.gopath
export PATH=$PATH:$HOME/.go/bin:$GOPATH/bin

# Haskell
export PATH=$HOME/.cabal/bin:$PATH

# Node
export NVM_DIR=$HOME/.nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# OCaml

# Perl
PATH="$HOME/perl5/bin${PATH+:}${PATH}"; export PATH;
PERL5LIB="$HOME/perl5/lib/perl5${PERL5LIB+:}${PERL5LIB}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"$HOME/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"; export PERL_MM_OPT;

# python
export PYENV_ROOT="${HOME}/.pyenv"
if [ -d "${PYENV_ROOT}" ]; then
  export PATH=${PYENV_ROOT}/bin:$PATH
  eval "$(pyenv init -)"
fi
PATH=~/.local/bin:$PATH

# Ruby
export GEM_HOME=$HOME/.local/lib/gems
export PATH=$HOME/.local/lib/gems/bin:$PATH
export PATH=$HOME/.gem/ruby/2.1.0/bin:$PATH

source ~/.zshrc.local

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
