# zsh
autoload -Uz colors
colors
PROMPT='%F{green}[%c@%m]%f '

HISTSIZE=5000
SAVEHIST=50000
HISTTIMEFORMAT='%Y-%m-%dT%H:%M:%S'
HISTFILE=${HOME}/.zsh_history
setopt extended_history
setopt hist_no_store
setopt hist_reduce_blanks
setopt share_history

autoload -U compinit && compinit

# homebrew
export HOMEBREW_NO_ANALYTICS=1

source ~/.zshrc.local
