[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_post_source = '''
" trailing-whitespace.txt {{{1
let g:extra_whitespace_ignored_filetypes = [
            \ 'ref-webdict',
            \ 'ref-rfc'
            \ ]
" End trailing-whitespace.txt }}}1
'''

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'ciaranm/detectindent'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/vim-asterisk'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
on_ft = ['julia']

[[plugins]]
repo = 'kana/vim-smartinput'
on_i = 1

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'vim-scripts/Gundo'

[[plugins]]
repo = 'vim-scripts/mru.vim'

[[plugins]]
repo = 'vim-scripts/project.tar.gz'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

