[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'ciaranm/detectindent'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/vim-asterisk'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
on_ft = ['julia']

[[plugins]]
repo = 'jvoorhis/coq.vim'
on_ft = ['coq']

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]]
repo = 'kana/vim-smartinput'
on_i = 1

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/wwwrenderer-vim'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'rhysd/unite-n3337'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'vim-scripts/Gundo'

[[plugins]]
repo = 'vim-scripts/mru.vim'

[[plugins]]
repo = 'vim-scripts/project.tar.gz'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

