---
- hosts: localhost
  gather_subset: '!ohai'
  connection: local
  vars:
    email: 1995.hnagamin@gmail.com
  roles:
    - commune
    - git
    - sonictemplate
    - spacemacs
    - tig
    - tmux
    - vim
    - zsh
