---
- name: ensure ~/.spacemacs.d exists
  file:
    path: ~/.spacemacs.d
    state: directory
- name: install .spacemacs
  copy:
    src: spacemacs
    dest: ~/.spacemacs.d/init.el
- stat:
    path: ~/.spacemacs.d/local-config.el
  register: local_config
- name: touch ~/.spacemacs.d/local-config.el
  command: touch ~/.spacemacs.d/local-config.el
  when: local_config.stat.exists == false
- name: ensure '~/.spacemacs.d/custom-set-variables.el' exists
  copy:
    src: custom-set-variables.el
    dest: ~/.spacemacs.d/custom-set-variables.el
    force: no
