---
- name: install sonictemplate files
  copy:
    src: "{{ item }}"
    dest: "~/.vim/sonictemplate/cpp/snip-{{ item | basename }}"
  with_fileglob:
    - data/*.cpp
    - graph/*.cpp
    - math/*.cpp
    - string/*.cpp
    - util/*.cpp
